CREATE TABLE ability  (
	id BIGINT NOT NULL PRIMARY KEY ,
	create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
	update_time TIMESTAMP WITH TIME ZONE NULL,
	row_version BIGINT NOT NULL DEFAULT 0,
	url VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL,
	base_time INTEGER NOT NULL,
	max_level SMALLINT NOT NULL,	
	CONSTRAINT ability_url_un UNIQUE (url)
);

CREATE SEQUENCE ability_seq MAXVALUE 9223372036854775807 NO CYCLE;